### ISSUE TITLE
Missing heather files in Windows build

### ISSUE THREAD

**Issue by massich** [conda-forge/libmatio-feedstock#12]
As mentioned in #11, the windows builds miss `matio.h` and `matio_pubconf.h`

**Comment by 183amir** [comment]
If you can fix it, please go ahead.

**Comment by traversaro** [comment]
The header files seems there in the last version of the package:
![headers](https://user-images.githubusercontent.com/1857049/140606005-aef7d222-6400-4f78-a5e3-69f4a3f5d290.PNG)

So I think we can close the issue. If this is not the case, feel free to open a new issue.
