### ISSUE TITLE
[RFC] CMake support

### ISSUE THREAD

**Issue by massich** [conda-forge/libmatio-feedstock#13]
I've been following the discussion in https://github.com/tbeu/matio/issues/53 and I think that in order to achieve give CMake support in matio there's an easier solution. Instead of switching matio's build system in favor of CMake or duplicating the build system (autoconf, and cmake), just adding a `matio-conf.cmake` in the conda package would be sufficient.

The `matio-conf.cmake` should only point to the needed heathers, the libraries and a list of all compiler requirements. In some manner, matio repository remains clean and binaries are shipped with CMake support from conda-forge.

(and all the custom and potentially buggy 'FindMatIO.cmake' modules on the internet would become unnecessary)

**Comment by massich** [comment]
I still think that for most of the projects providing `matio-conf.cmake` should be enough. However, if anyone wants to build matio using **CMake** you can check out [matio-cmake](https://github.com/massich/matio-cmake) which has matio as a submodule. 

So to build a particular version of matio, just checkout the submodule at the desired commit and run cmake.

**Comment by 183amir** [comment]
> just adding a matio-conf.cmake in the conda package would be sufficient.

It's not a good idea to change the package here instead of changing it in upstream. It means you are basically forking matio without renaming it! This is really bad. You can see one example here: https://tingping.github.io/2018/03/02/when-distros-get-it-wrong.html

If you want to **just** add something, please do it upstream.

**Comment by massich** [comment]
I don't really see the relation between the two. I was not suggesting any change on the code base. I suggested to have cmake config file describing what is provided by the package could be nice to have within the package. In the same manner that you could have a package description in a TXT saying where are the headers/lib placed and which are the compilation flags. I was not suggesting to add a cmake building system that could deviate from upstream.

But I also understand that having a cmake building system upstream exporting `matio-conf.cmake` would be a more desirable solution.
