### ISSUE TITLE
libmatio.lib import library

### ISSUE THREAD

**Issue by agramfort** [conda-forge/libmatio-feedstock#18]
looking at:

lib /list C:\conda\Library\lib\libmatio.lib

it seems that the libmatio.lib shipped is not a windows static library but a so-called import library [1]

it means that when linking against C:\conda\Library\lib\libmatio.lib the app produced
needs C:\conda\Library\bin\libmatio.dll

this makes it difficult to ship standalone applications, unless we hack our package system to copy the dll manually.

do you see an alternative? could the .lib on this conda build corresponds to a real static lib? note that on linux and mac we get both an archive .a and a shared lib (.so or .dylib)

[1] https://stackoverflow.com/questions/6402586/know-if-lib-is-static-or-import

cc @massich

**Comment by massich** [comment]
apparently, the objects generated by [matio-cmake](https://github.com/massich/matio-cmake) are correct:

```sh
E:\matio\build>lib /list Debug\matio.lib
Microsoft (R) Library Manager Version 14.12.25835.0
Copyright (C) Microsoft Corporation.  All rights reserved.

matio.dir\Debug\endian.obj
matio.dir\Debug\mat.obj
matio.dir\Debug\io.obj
matio.dir\Debug\inflate.obj
matio.dir\Debug\mat73.obj
matio.dir\Debug\matvar_cell.obj
matio.dir\Debug\matvar_struct.obj
matio.dir\Debug\mat4.obj
matio.dir\Debug\mat5.obj
matio.dir\Debug\snprintf.obj
matio.dir\Debug\read_data.obj

E:\matio\build>
```

maybe we can compare the generated `.sln` file generated by cmake to get some clues.

**Comment by agramfort** [comment]
this issue is also related to https://github.com/tbeu/matio/pull/89

@tbeu do you see a way forward here?

**Comment by tbeu** [comment]
Yes, should be no problem to compile as static lib.

**Comment by agramfort** [comment]
so are you fine if we migrate the .sln to static so the conda package ships
a static lib?

**Comment by traversaro** [comment]
Given the recent CFEP-18 (https://github.com/conda-forge/cfep/blob/master/cfep-18.md) that was not there at the original time of the discussion, if someone wants to also package a static variant of `libmatio` it should do so by providing an additional `libmatio-static` output, instead of replacing the existing shared build. Given this, I think we can close the issue, anyone interesting in static library should prepare a PR compliant with CFEP-18 .
